# Generated by Django 4.0.4 on 2022-05-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('django', 'Django'), ('spring', 'Spring'), ('asp.net', 'Asp.net'), ('node.js', 'Node.js'), ('ruby on rails', 'Ruby on Rails')], max_length=20)),
                ('frontend', models.CharField(choices=[('react', 'React'), ('angular', 'Angular'), ('vue', 'Vue.js')], max_length=20)),
                ('database', models.CharField(choices=[('mysql', 'MySQL'), ('mssql', 'Microsoft SQL Server'), ('postgres', 'PostgreSQL'), ('oracle', 'Oracle')], max_length=20)),
            ],
        ),
    ]
